spring.application.name=customer-service
server:
port: 8080

spring:
application:
name: customer-service

eureka:
client:
service-url:
defaultZone: http://localhost:8761/eureka

spring.datasource.url=jdbc:h2:file:./data/customerdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

gateway.base-url=http://localhost:8086

spring.cloud.gateway.routes[10].id=customer-swagger
spring.cloud.gateway.routes[10].uri=lb://CUSTOMER-SERVICE
spring.cloud.gateway.routes[10].predicates[0]=Path=/customer-api-docs/**
spring.cloud.gateway.routes[10].filters[0]=RewritePath=/customer-api-docs/(?<segment>.*), /${segment}
