spring.application.name=loan-service
server.port=8083


spring.datasource.url=jdbc:h2:file:./data/loandb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

gateway.base-url=http://localhost:8086

spring.cloud.gateway.routes[11].id=loan-swagger
spring.cloud.gateway.routes[11].uri=lb://LOAN-SERVICE
spring.cloud.gateway.routes[11].predicates[0]=Path=/loan-api-docs/**
spring.cloud.gateway.routes[11].filters[0]=RewritePath=/loan-api-docs/(?<segment>.*), /${segment}